### ISSUE TITLE
Ser2Net support

### ISSUE THREAD

**Issue by QempZor** [ebaauw/homebridge-p1#11]
Hello, would it be possible to use ser2net?
My Homebridge RPi is somewhere else in my home. 
I use a dedicated RPi as ser2net for DSMR.

**Comment by ebaauw** [comment]
I’m unfamiliar with ser2net.  homebridge-p1 accesses the serialport directly to contact the smart meter’s P1 interface.  I suppose you could run another instance of HomeKit on the RPi running ser2net, but I fear only one process at a time can open the serialport, see #5.
