### ISSUE TITLE
Installation failed with ENOENT for serialport depency

### ISSUE THREAD

**Issue by w0utert** [ebaauw/homebridge-p1#14]
When trying to install homebridge-p1, I get the following error:

```
npm ERR! path /usr/lib/node_modules/homebridge-p1/node_modules/serialport/bin/list.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/homebridge-p1/node_modules/serialport/bin/list.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wouter/.npm/_logs/2018-11-30T12_11_58_541Z-debug.log
```

This is using up-to-date NodeJS, homebridge etc:

```
[11/30/2018, 1:10:49 PM] Loading 1 platforms...
[11/30/2018, 1:10:49 PM] [Hue] Initializing Hue platform...
[11/30/2018, 1:10:49 PM] [Hue] homebridge-hue v0.11.1, node v10.14.0, homebridge v0.4.45
[11/30/2018, 1:10:49 PM] [Hue] warning: not using recommended node version v10.13.0 LTS
```

I've tried to remove all globally installed node modules and re-installing, manually installing serialport, etc, but installation still fails. The same error presents itself when installing e.g. homebridge-p1 0.10.1.

-Wouter

**Comment by ebaauw** [comment]
What platform are you on?  What command do you use to install homebridge-p1?

**Comment by w0utert** [comment]
I'm using Ubuntu server 16.04.5, with NodeJS 10 installed from the deb.nodesource.com/node_10.x repo. 
Interestingly, the error message was identical when I tried to install using the stock NodeJS 8.x that comes with Ubuntu 16.04, so it does not seem to be related to the upgrade.

The command I'm using to install is this:

`# sudo npm -g install homebridge-p1 --unsafe-perm`

I can install and use other packages through NPM without problems.

Thanks, Wouter

**Comment by ebaauw** [comment]
Looks like serialport@7.1.0, released 4 days ago, no longer ships the binaries, nor the `bin` directory.  I don't know why; I particularly liked `serialport-list` for debugging.

I specified `"serialport": "^7.0.2"` as a dependency for homebridge-p1, thinking it would only accept (non-breaking) updates to the patch level.  Apparently, that's only true when the major version is 0, so `npm` now installs serialport@7.1.0.  I should have used `"serialport": "~7.0.2"`.  I'm afraid the same holds for all other dependencies...

**Comment by ebaauw** [comment]
v0.2.1 should install without any errors.

**Comment by w0utert** [comment]
Gotta love npm ;-/

I just installed 2.0.1 successfully. Thanks for the quick fix!

-Wouter

**Comment by ebaauw** [comment]
Link: https://github.com/node-serialport/node-serialport/issues/1732
