### ISSUE TITLE
Installation failed Homebridge plugin for DMSR end-consumer (P1) interface  version 0.2.4

### ISSUE THREAD

**Issue by pjansen75** [ebaauw/homebridge-p1#15]
Hello,
I tried to install the plugin in Homebridge on Docker, but installation failed.
This is the error I received:

> @serialport/bindings@2.0.6 install /homebridge/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.3 runtime=node arch=arm platform=linux)
make: Entering directory '/homebridge/node_modules/@serialport/bindings/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
../src/serialport_unix.cpp:24:26: fatal error: linux/serial.h: No such file or directory

                          ^
compilation terminated.
make: *** [bindings.target.mk:96: Release/obj.target/bindings/src/serialport_unix.o] Error 1
make: Leaving directory '/homebridge/node_modules/@serialport/bindings/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.50-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/@serialport/bindings
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.6 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @serialport/bindings@2.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-17T20_26_55_446Z-debug.log

I hope, someone can help me with this?

**Comment by ebaauw** [comment]
homebridge-zp relies on the [serialport](https://github.com/node-serialport/node-serialport) module to interact with the P1 port.  This module contains C code which needs to be compiled on the system it installs to.  You need to make sure your container has the necessary development tools installed.  I cannot help you with that.

**Comment by denn1987** [comment]
> homebridge-zp relies on the [serialport](https://github.com/node-serialport/node-serialport) module to interact with the P1 port. This module contains C code which needs to be compiled on the system it installs to. You need to make sure your container has the necessary development tools installed. I cannot help you with that.

Hi Ebaauw,

I have the same error while installing the plugin. Can you explain what you mean by necessary development tools witch I need to install?

**Comment by ebaauw** [comment]
See https://serialport.io/docs/en/guide-installation

**Comment by denn1987** [comment]
> See https://serialport.io/docs/en/guide-installation

Thanks! This helps me a little further. Now I have the following log when I start HomeBridge.
Can it be that the warning causes the error? 

![image](https://user-images.githubusercontent.com/35924558/53121742-2aea4800-3555-11e9-95c5-ba87e71f4cc1.png)

**Comment by ebaauw** [comment]
Most likely the wrong USB port, or the user running homebridge has no permission to open the port.
 
What is the output of `serialport-list` (when run from the container)?

**Comment by denn1987** [comment]
Sorry I'm new to domoticz and raspberry but when I use the command I get no output.
I use the P1 meter in domoticz and there it runs ok so I think it is the correct USB port. I receive the data from my gas and enery meter.
I can see the gas and energy meter in Homekit apple but it says "Not appropiate".
![image](https://user-images.githubusercontent.com/35924558/53124807-9be12e00-355c-11e9-9457-c34bb54ca674.png)

**Comment by ebaauw** [comment]
Apple's Home app doesn't support custom services and characteristics, you need to use another HomeKit app, like Eve.

If domiticz has already opened the port, homebridge-p1 won't be able to open it.

You need to expose the port in the container that homebridge runs in.

**Comment by denn1987** [comment]
Thanks! I will give it a try.
