### ISSUE TITLE
Less logging

### ISSUE THREAD

**Issue by RienduPre** [ebaauw/homebridge-p1#16]
Hi,

The plugin is logging every 10 seconds the total and current consumption. Can this be suppressed by setting a logging option or  so?
My Homebridge log is flooded by these messages.

Thanks,
Rien

**Comment by ebaauw** [comment]
There's no way in homebridge-p1 to suppress the log messages.

The log (and debug) messages are written to stdout; warnings and errors are written to stderr.  You could redirect stdout to /dev/null and only capture stderr in your log.

**Comment by sebastiaan88** [comment]
Is there a possibility already to change this? My meter has DSMR 5 so it gets data every second, and the RPI seems to stop parsing the data after 2 days or so, homebridge still runs and functions but theres no new data from p1 or even history. When I reboot homebridge it runs fine again...
