### ISSUE TITLE
Warning with two key's

### ISSUE THREAD

**Issue by steenau** [ebaauw/homebridge-p1#19]
Hello Eric,

Your plugin is working great.  I only have 2 key's who are not supported. I assume this is the Gas....

<img width="1156" alt="Schermafbeelding 2019-06-10 om 12 14 13" src="https://user-images.githubusercontent.com/7723720/59189603-c3471f80-8b7a-11e9-9061-e10c4e53f577.png">

**Comment by ebaauw** [comment]
> I assume this is the Gas....

I don't think so.  They start with `0-0:` which usually means they're about the meter itself.  Also, the `17.0.0` value is in kW, where gas is usually in m3.

Could you please capture a debug log file (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and attach that?  Homebridge-p1 logs the first telegram when homebridge starts with `-D`.  Did you have to set `dsmr22` or was your meter recognised by default?
