### ISSUE TITLE
Support for 3-phase electricity installations?

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-p1#2]
Currently, homebridge-p1 only reports voltage and electric current for phase 1 and (current) consumption for all phases combined.  This suffices for most consumers, like me, who have a single-phase electricity installation.

The smart meter actually supports 3-phase installations as well, reporting separate (current) consumption, voltage and electric current per phase.  Technically it would be possible to expose these to HomeKit.  It would have to be through a separate accessory, not in interfere with the history in Eve.  Alternatively, homebridge-p1 could report the average voltage and total electric current for the combined phases.

Please let me know your views on this.

**Comment by macdivernl** [comment]
Sorry for not having found this threat...

Separate 'devices' like temperature meters with e.g. PowerConsumption L1, PowerConsumption L2, PowerConsumption L3 would be awesome for me.
It would be interesting to have Apple Home be able to automatically switch devices on / off according to current power use. (read: Capacity).

( If power consumption L3 > 3800 AND Temperature < 5C, switch off Electrical Car Charging and switch on Electrical Heater )

**Comment by ebaauw** [comment]
Would you need consumption history per phase?  If so, I’ll have to expose three additional accessories, one for each phase, each with their own Eve history.  If not, I could expose a single extra accessory with a service per phase.  What version of DSMR does your meter expose?  Could you run `homebridge -D` and post the telegram homebridge-p1 logs?

Consumption is a numeric attribute, so you should be able to use it in HomeKit automations.  I haven’t tried this myself, though.  Not sure if Apple’s Home app will support this, but you can probably set up the automations in Eve.

**Comment by macdivernl** [comment]
Is this what you're asking for?

[P1] raw data: {"type":"ISK5\\2M550T-1012","checksum":"58E5","version":"5.0","lastupdated":"2019-12-29T23:37:14","id":"E0044007118000000","consumption_low":4000.647,"consumption_normal":1154.948,"consumption_back_low":0,"consumption_back_normal":0,"tariff":"low","power":1765,"power_back":0,"failures_short":9,"failures_long":4,"log":{"2018-03-27T06:41:11":180,"2019-01-08T10:59:23":2603},"l1_sags":1,"l2_sags":1,"l3_sags":1,"l1_swells":1,"l2_swells":1,"l3_swells":1,"msg_text":null,"l1_voltage":236.9,"l2_voltage":235.1,"l3_voltage":234.9,"l1_current":0,"l2_current":0,"l3_current":6,"l1_power":132,"l2_power":37,"l3_power":1596,"l1_power_back":0,"l2_power_back":0,"l3_power_back":0}

[P1] data: {"type":"ISK5\\2M550T-1012","version":"5.0","msg_text":null,"electricity":{"id":"E0044007118000000","lastupdated":"2019-12-29T23:37:14","tariff":"low","consumption":{"low":4000.647,"normal":1154.948},"power":1765,"failures":{"short":9,"long":4,"log":{"2018-03-27T06:41:11":180,"2019-01-08T10:59:23":2603}},"l1":{"voltage":236.9,"sags":1,"swells":1,"current":0,"power":132},"l2":{"voltage":235.1,"sags":1,"swells":1,"current":0,"power":37},"l3":{"voltage":234.9,"sags":1,"swells":1,"current":6,"power":1596}},"electricityBack":{"id":"E0044007118000000B","lastupdated":"2019-12-29T23:37:14","tariff":"low","consumption":{"low":0,"normal":0},"power":0,"l1":{"power":0},"l2":{"power":0},"l3":{"power":0}}}


[12/29/2019, 11:37:16 PM] [P1] ISK5\2M550T-1012 v5.0
[12/29/2019, 11:37:16 PM] [P1] Initializing platform accessory 'Electricity'...

[12/29/2019, 11:37:14 PM] [P1] listening on /dev/ttyUSB0
[12/29/2019, 11:37:16 PM] [P1] telegram:
/ISK5\2M550T-1012

1-3:0.2.8(50)
0-0:1.0.0(191229233714W)
0-0:96.1.1(4530303434303037313138353239333138)
1-0:1.8.1(004000.647*kWh)
1-0:1.8.2(001154.948*kWh)
1-0:2.8.1(000000.000*kWh)
1-0:2.8.2(000000.000*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(01.765*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00009)
0-0:96.7.9(00004)
1-0:99.97.0(2)(0-0:96.7.19)(180327064111S)(0000000180*s)(190108105923W)(0000002603*s)
1-0:32.32.0(00001)
1-0:52.32.0(00001)
1-0:72.32.0(00001)
1-0:32.36.0(00001)
1-0:52.36.0(00001)
1-0:72.36.0(00001)
0-0:96.13.0()
1-0:32.7.0(236.9*V)
1-0:52.7.0(235.1*V)
1-0:72.7.0(234.9*V)
1-0:31.7.0(000*A)
1-0:51.7.0(000*A)
1-0:71.7.0(006*A)
1-0:21.7.0(00.132*kW)
1-0:41.7.0(00.037*kW)
1-0:61.7.0(01.596*kW)
1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
!58E5

**Comment by ebaauw** [comment]
Yes, thanks.

**Comment by macdivernl** [comment]
Oh FYI: I'm not using gas (stadsverwarming too here) and I'm not supplying power back to the net (no solar).

**Comment by ebaauw** [comment]
Yeah, I figured that from the meter data.  The DSMR standard seems to accommodate for city heating, but I have never seen that in real life.

The meter doesn’t report cumulative consumption per phase; I’m not sure how reliably I can compute this from the power over time.  You have a DSMR 5.0 meter, which should update the reading every second.

**Comment by macdivernl** [comment]
> Yeah, I figured that from the meter data. The DSMR standard seems to accommodate for city heating, but I have never seen that in real life.
> 
> The meter doesn’t report cumulative consumption per phase; I’m not sure how reliably I can compute this from the power over time. You have a DSMR 5.0 meter, which should update the reading every second.

current use would be fine for me.

**Comment by ebaauw** [comment]
Could you try v0.2.30-6?  Install through:
```
$ sudo npm -g i homebridge-p1@beta --unsafe-perm
```

This version should expose three additional services to the _Electricity_ accessory.  These services contain _Current Consumption_, _Electric Current_, and _Voltage_ per phase.  The main service also contains _Current Consumption_, which should be the total consumption over the three phases, as reported by the meter.

Note: when the meter doesn't show three-phase electricity, _Electric Current_ and _Voltage_ are exposed under the main service and no additional services are exposed.

**Comment by ebaauw** [comment]
@macdivernl, can you please confirm that the latest version works with three-phase electricity?

**Comment by jeroen020** [comment]
I just received a P1 - USB cable, configured this plugin on an old Raspberry running HOOBS and it works with 3 phases, the log looks like this:

```
[Homebridge] [2/8/2020, 1:59:48 PM] [P1] Electricity: set homekit total consumption from 4672.602 kWh to 4672.603 kWh
[Homebridge] [2/8/2020, 1:59:48 PM] [P1] Electricity: set homekit total consumption low from 2398.165 kWh to 2398.166 kWh
[Homebridge] [2/8/2020, 1:59:49 PM] [P1] Electricity: set homekit current consumption from 799 W to 802 W
[Homebridge] [2/8/2020, 1:59:49 PM] [P1] Electricity L1: set homekit voltage from 231.4 V to 231.3 V
[Homebridge] [2/8/2020, 1:59:49 PM] [P1] Electricity L2: set homekit current consumption from 55 W to 54 W
[Homebridge] [2/8/2020, 1:59:49 PM] [P1] Electricity L2: set homekit voltage from 231.2 V to 231.1 V
[Homebridge] [2/8/2020, 1:59:49 PM] [P1] Electricity L3: set homekit current consumption from 45 W to 46 W
[Homebridge] [2/8/2020, 1:59:49 PM] [P1] Electricity L3: set homekit voltage from 231 V to 231.1 V
[Homebridge] [2/8/2020, 1:59:49 PM] [P1] Electricity L1: set homekit current consumption from 700 W to 703 W
[Homebridge] [2/8/2020, 1:59:50 PM] [P1] Electricity L1: set homekit voltage from 231.3 V to 231.2 V
[Homebridge] [2/8/2020, 1:59:50 PM] [P1] Electricity L2: set homekit current consumption from 54 W to 55 W
[Homebridge] [2/8/2020, 1:59:50 PM] [P1] Electricity L2: set homekit voltage from 231.1 V to 231.2 V
[Homebridge] [2/8/2020, 1:59:50 PM] [P1] Electricity L3: set homekit current consumption from 46 W to 43 W
```
In the Eve app, I get Electricity consumed in kWh and current usage (W, A & V) for L1, L2 and L3 separately. I don't see the current consumption (3rd line above) which for me would be the most useful info.

**Comment by ebaauw** [comment]
Could you please capture and attach a debug log file, see above?  

There should be a _Total Consumption_ and _Consumption_ on the main service, and an additional _Consumption_ on each phase service.  Did you try _Edit_ in the accessory window, to see if there's any hidden characteristics?  If not, could you please post a screenshot of the accessory window

**Comment by jeroen020** [comment]
> Could you please capture and attach a debug log file, see above?

Hmm, I'm using HOOBS that starts automatically, I can't seem to get it to run in debug mode. When I have some more time I can try to set up homebridge-p1 on my main Homebridge where I can examine better.

> There should be a Total Consumption and Consumption on the main service, and an additional Consumption on each phase service. Did you try Edit in the accessory window, to see if there's any hidden characteristics? If not, could you please post a screenshot of the accessory window?

Ah, I see it now - when I check the room view in Eve app, I see 'Electricity' in kWH but when I select that, in the following screen shows a lot more detail, including 'Consumption' which is the total of L1, L2 and L3. I don't see how I can show this in the room screen itself though.

![IMG_0635](https://user-images.githubusercontent.com/40571458/74105241-62824380-4b5c-11ea-9996-58b7d3b9b2b7.png)
![IMG_0637](https://user-images.githubusercontent.com/40571458/74105244-6615ca80-4b5c-11ea-8c1e-8a206da80c13.png)
![IMG_0638](https://user-images.githubusercontent.com/40571458/74105248-69a95180-4b5c-11ea-8751-4409ff72c464.png)

**Comment by ebaauw** [comment]
> I don't see how I can show this in the room screen itself though.

That's up to Eve.  It only shows one line per service in the room view.  It shows what it consideres the main characteristic in a bug font, and sometimes some secondary characteristics in a smaller font.  I haven't found any way to influence this behaviour.

From the screenshot, it looks like you have solar panels?  Is the electricity delivered back indeed reported per phase?

**Comment by jeroen020** [comment]
> From the screenshot, it looks like you have solar panels? Is the electricity delivered back indeed reported per phase?

Indeed, I have solar panels; will need to wait for better weather before I can check how it shows up in the app. Youless only reports the aggregate, not per phase.

**Comment by macdivernl** [comment]
> @macdivernl, can you please confirm that the latest version works with three-phase electricity?

It does!!
