### ISSUE TITLE
Possibility labels to change the labels

### ISSUE THREAD

**Issue by steenau** [ebaauw/homebridge-p1#20]
Hello Eric,

It would be nice to setup the labels in the config.json file for:
Electricity and Electricity Delivered.
Then it would be possible to make it: "Verbruikt" and "Geleverd" or something like that.

**Comment by ebaauw** [comment]
You should be able to change the accessory and service (Siri) names in Eve.

Only the initial names (when the accessory is first exposed) can be set through HAP (i.e. by the accessory itself, or in our case by homebridge).

**Comment by steenau** [comment]
I did but still in the view the old name. See screenshot. But also the 'Home/Woning' app doesn't display the correct name.
![IMG_F548305FF5C6-1](https://user-images.githubusercontent.com/7723720/59192551-14f3a800-8b83-11e9-8b8e-8f0ccb598a49.jpeg)

**Comment by ebaauw** [comment]
Odd, normally Eve shows a _Name_, _Names_, _Name & Type_ or _Names & Types_ setting right under _Room_ in the accessory settings, to set the name of the services, (a.k.a. Siri name).  For some reason, it doesn't show this for the homebridge-z1 accessories.

You can set the name in Apple's Home app, though.  This changes both the accessory and service name.

**Comment by steenau** [comment]
Restart everything but still the Eve 3.7.2 on a iPhone Xs shows this. Not a big problem but for that reason I thought it would be nice to set it up in the config.json.
![IMG_4F0F6ACAD9F8-1](https://user-images.githubusercontent.com/7723720/59248942-09a48900-8c24-11e9-89be-e943791450d6.jpeg)
