### ISSUE TITLE
No accessories in Eve for P1

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-p1#21]
Since the last 2 days the P1 accessory keeps disappearing in the Eve app. After a fresh restart the accessory is visible but disappears within a few hours. The log shows that P1 is recording the values. Any idea wha5 goes wrong?

**Comment by ebaauw** [comment]
Does homebridge crash and restart?  Homebridge-p1 won’t block the startup of homebridge if it cannot find the smart meter within the timeout period.  You might set a longer timeout in config.json.  See https://github.com/ebaauw/homebridge-p1#configuration.

**Comment by tomsteenbakkers** [comment]
I have changed the timeout but the P1 accessory keeps disappearing after several minutes. Only a reboot will solve the problem. Idea where I can start to find the problem?

It's still losing the data:
```
[7/2/2019, 8:50:53 AM] [P1] Electricity: set homekit total consumption from 25521.625 kWh to 25521.627 kWh
[7/2/2019, 8:50:53 AM] [P1] Electricity: set homekit total consumption normal from 14766.946 kWh to 14766.948 kWh
[7/2/2019, 8:50:53 AM] [P1] Electricity: set homekit current consumption from 779 W to 781 W 
```

**Comment by ebaauw** [comment]
Several minutes after what?  Does homebridge restart before the accessory disappears?  Reboot of what?  On one iOS device or on multiple?

Does this still happen when you run homebridge-p1 as only plugin?

**Comment by tomsteenbakkers** [comment]
I do not see anything in the log why the accessory is disappearing. It is just disappearing after the reboot. So there is no event in the log which I can relate.

Homebridge is also no restarting before the accessory disappears. I have checked that with the uptime of homebridge. 

The accessory will appear when I restart Homebridge or a reboot of the RaspberryPI. The disappearing  happens on all iOS devices (iPad and iPhone).

I will try tonight to disable all the other plugins, see what's happening.

**Comment by tomsteenbakkers** [comment]
Started the search for the disappearing of the accessories. During the homebridge startup I see these following warnings. What does this mean?

![C8783B1A-726B-4E7C-B7DA-D0668C76FEDA](https://user-images.githubusercontent.com/24613800/60547628-79d49500-9d20-11e9-89f3-d7d72db43190.jpeg)

**Comment by ebaauw** [comment]
That NodeJS fired the heartbeat timer too late.  I wouldn’t worry if this happens once or twice shortly after starting homebridge, but almost 3 seconds (2753 ms) is a long time.  Could be an indication that a plugin is doing synchronous I/O, or otherwise blocking NodeJS.  Wouldn’t explain the disappearing accessories, though.

**Comment by tomsteenbakkers** [comment]
I removed the home and reset the home app. Now things are back to normal. Strange. Thanks for the support.
