### ISSUE TITLE
Eve app update and missing graphs

### ISSUE THREAD

**Issue by rooi** [ebaauw/homebridge-p1#22]
Hi,

Thanks for this plugin! Yesterday’s eve app updated resulted in missing graphs for the p1 accessory. Other accessories, native eve ones and others using elgato-history still work (although they seem to have removed some graph ui functions.
Does the same happen on you setup?

Thanks

Roy

**Comment by ebaauw** [comment]
Yes, unfortunately.  Eve 3.8.1 seems more restrictive on what an accessory must look like to enable history.  It no longer seems to accept the custom service I use for the smart meters.  I might have to expose these using the _Outlet_ service, but that comes with an _On_ characteristic, which makes no sense for a smart meter.

**Comment by ebaauw** [comment]
In v0.2.25.

**Comment by rooi** [comment]
Great!
