### ISSUE TITLE
/dev/ttyUSB0: port not found

### ISSUE THREAD

**Issue by jespertheend** [ebaauw/homebridge-p1#23]
Hi

I can't seem to get this to work. Homebridge keeps logging that `/dev/ttyUSB0: port not found`
I have homebridge running as a system service with user `homebridge` and I have enabled the `-D` flag. Here's my log:

```
[11/11/2019, 9:46:55 PM] [P1] Initializing P1 platform...
[11/11/2019, 9:46:56 PM] [P1] homebridge-p1 v0.2.27, node v10.16.3, homebridge v0.4.50
[11/11/2019, 9:46:56 PM] [P1] warning: not using recommended node version v12.13.0 LTS
[11/11/2019, 9:46:56 PM] [P1] config.json: {"platform":"P1","serialport":"/dev/ttyUSB0"}
[11/11/2019, 9:47:02 PM] [P1] ports: []
[11/11/2019, 9:47:02 PM] [P1] /dev/ttyUSB0: port not found
```

I have tried several things in the config, dsmr22 doesn't seem to work. Excluding the `serialport` from the config doesn't seem to work either.

I can't seem to install `serialport-list` but I can see /dev/ttyUSB0 appearing and disappearing when I plug/unplug the P1 cable. And `lsusb` reports
```
Bus 001 Device 002: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

I've also added the `homebridge` user to the `dialout` group, which I think is the owner of `ttyUSB0`.

Earlier when I did `cat /dev/ttyUSB0` I saw binary data getting logged every second. So it seemed like it was working correctly, but I can now no longer reproduce this.

**Comment by ebaauw** [comment]
> [11/11/2019, 9:47:02 PM] [P1] ports: []

homebridge-p1 hasn’t found any serialport.  What system are you on?

> I can't seem to install `serialport-list`

That uses the same NodeJS module as homebridge-p1 to access the serial port.  It makes use of some C component, which needs to be compiled on installation.

**Comment by jespertheend** [comment]
I’m on a raspberry pi zero. Though I’m wondering now if the usb cable might be pulling too much power. Sometimes when I plug it in I’m completely unable to ssh into the pi.

I seem to be having issues with binary files not getting added properly so I can’t use their alias on the command line directly. I wasn’t aware serialport-list came with this repository. I’ll try again tomorrow without the alias.

**Comment by ebaauw** [comment]
> Though I’m wondering now if the usb cable might be pulling too much power.

What power supply are you using with the Pi Zero?  USB should only draw up to 500mW.

> I seem to be having issues with binary files not getting added properly so I can’t use their alias on the command line directly.

Strictly speaking these aren't binary files; they're JavaScript files, that are run by NodeJS.

> I wasn’t aware serialport-list came with this repository.

Not anymore.  You need to install it separately using
```
$ sudo npm -g i @serialport/list --unsafe-perm
```
`npm` should create a symlink (alias) in `/usr/bin/serialport-list` (or `/usr/local/bin/serialport-list` depending on how you installed NodeJS).  If it doesn't, this might indicate an install error, maybe failed compilation of the C component.

Note that, after upgrading NodeJS to a different major version, you need to force re-compilation of the C component.  Best uninstall (`sudo npm -g un ...`) and re-install (`sudo npm -g i ... --unsafe-perm`).

**Comment by wardmans** [comment]
I'm having the exact same issue but I'm on a Raspberry Pi 3b+. I manually installed `serial port-list`. I did do a major upgrade from  `NodeJS` 10 to 12.13.0  but I uninstalled and reinstalled the plugin and the symlink is there. 

```
pi@raspberrypi:/ $ /usr/local/bin/serialport-list
/dev/ttyAMA0
/dev/ttyUSB0	usb-FTDI_FT232R_USB_UART_AM3ES2GH-if00-port0	FTDI

```

Though Homebridge P1 is unable to find the USB device.

```
[11/13/2019, 3:39:43 PM] ---
[11/13/2019, 3:39:49 PM] Loaded plugin: homebridge-p1
[11/13/2019, 3:39:49 PM] Registering platform 'homebridge-p1.P1'
[11/13/2019, 3:39:49 PM] ---
[11/13/2019, 3:40:00 PM] [P1] Initializing P1 platform...
[11/13/2019, 3:40:00 PM] [P1] homebridge-p1 v0.2.27, node v12.13.0, homebridge v0.4.50
[11/13/2019, 3:40:02 PM] [P1] /dev/ttyUSB0: port not found
```

**Comment by ebaauw** [comment]
Did you double-check the permissions?  Is the user running homebridge a member of the `dialout` group?

**Comment by wardmans** [comment]
Homebridge is running under the user homebridge which wasn't a member of the `dialout` group. 
```
pi@raspberrypi:~ $ groups homebridge
homebridge : homebridge dialout
```
I've added the user to the group, rebooted the pi but the issue P1 still can't find the USB port.

**Comment by ebaauw** [comment]
What version of Raspbian are you on?  What’s the output of `ls -l /dev/ttyUSB0`?  What happens if you run `serialport-list` as user `homebridge`?

**Comment by wardmans** [comment]
> ls -l /dev/ttyUSB0

The output is `crw-rw---- 1 root dialout 188, 0 Nov 14 09:33 /dev/ttyUSB0`
I'm on a Raspberry Pi 3 Model B Plus Rev 1.3

When I run serial port-list as the user running homebridge (homebridge in my case) there is no response. When I run it as root there is a response.

```
root@raspberrypi:/home/pi# runuser -l homebridge -c serialport-list
root@raspberrypi:/home/pi# serialport-list
/dev/ttyAMA0		
/dev/ttyUSB0	usb-FTDI_FT232R_USB_UART_AM3ES2GH-if00-port0	FTDI
```

But when I run the serialport-terminal command under user homebridge, I do get output from the meter.
```
root@raspberrypi:/usr/local/bin# runuser -l homebridge -c 'serialport-terminal -p /dev/ttyUSB0 -b 112500'
Opening serial port: /dev/ttyUSB0 echo: true
/KFM5KAIFA-METER



1-3:0.2.8(42)

0-0:1.0.0(191118142201W)

0-0:96.1.1(4530303236303030303333363037333136)

1-0:1.8.1(006242.689*kWh)

1-0:1.8.2(005460.971*kWh)

1-0:2.8.1(000782.939*kWh)

1-0:2.8.2(001930.043*kWh)

0-0:96.14.0(0002)

1-0:1.7.0(00.428*kW)

1-0:2.7.0(00.000*kW)

0-0:96.7.21(00004)

0-0:96.7.9(00002)

1-0:99.97.0(3)(0-0:96.7.19)(191102131254W)(0000013696*s)(170624162352S)(0000002384*s)(000101000137W)(2147483647*s)
...
```

**Comment by ebaauw** [comment]
Are you running Raspbian Stretch or Buster?

> When I run serial port-list as the user running homebridge (homebridge in my case) there is no response. When I run it as root there is a response.

I'm not too familiar with `runuser` (I never login as `root` and use `sudo` if I need to run a privileged command), but if `serialport-list` fails (returns nothing) for user `homebridge`, this would suggest a privilege issue.  I'm afraid this is beyond me.

> But when I run the serialport-terminal command under user homebridge, I do get output from the meter.

That's good.  I'll see if I can issue a warning and bluntly open the port specified in config.json instead of insisting that it is (also) returned by searching for ports.

**Comment by wardmans** [comment]
> Are you running Raspbian Stretch or Buster?
I'm running Buster

Normally I use `sudo` as well when I need to run a privileged command. I'll see if I can find anything that's related to insufficient privileges.

**Comment by ebaauw** [comment]
Bingo!  Buster needs (an) additional group(s) to list the ports.  With only group `dialout`, I don't see any; with the default group list for user `pi`, I do see them.  Not sure which group it is, but the full list is:
```
$ groups
pi adm dialout cdrom sudo audio video plugdev games users input netdev gpio i2c spi
```

**Comment by wardmans** [comment]
Bingo indeed! I've added the homebridge user to the gpio group, restarted homebridge and it works immediately. 

```
[11/18/2019, 9:54:21 PM] [P1] KFM5KAIFA-METER v4.2
[11/18/2019, 9:54:21 PM] [P1] data received too late - see README
[11/18/2019, 9:54:31 PM] [P1] Electricity: set homekit total consumption from 11709.42 kWh to 11709.422 kWh
[11/18/2019, 9:54:31 PM] [P1] Electricity: set homekit total consumption low from 6243.134 kWh to 6243.136 kWh
[11/18/2019, 9:54:31 PM] [P1] Electricity: set homekit current consumption from 528 W to 536 W
[11/18/2019, 9:54:41 PM] [P1] Electricity: set homekit total consumption from 11709.422 kWh to 11709.423 kWh
[11/18/2019, 9:54:41 PM] [P1] Electricity: set homekit total consumption low from 6243.136 kWh to 6243.137 kWh
[11/18/2019, 9:54:41 PM] [P1] Electricity: set homekit current consumption from 536 W to 541 W
```

Thanks for the support!

**Comment by ebaauw** [comment]
Cool.

> [11/18/2019, 9:54:21 PM] [P1] data received too late - see README

I don't think homebridge-p1 exposes any accessory.  You might want to increase the `timeout` setting in config.json.

**Comment by wardmans** [comment]
Correct. By setting `"timeout": 20` homebridge exposes 3 accessories. 

```
[11/18/2019, 10:23:20 PM] [P1] KFM5KAIFA-METER v4.2
[11/18/2019, 10:23:20 PM] [P1] Initializing platform accessory 'Electricity'...
[11/18/2019, 10:23:20 PM] [P1] Initializing platform accessory 'Electricity Delivered'...
[11/18/2019, 10:23:20 PM] [P1] Initializing platform accessory 'Gas'...
```
