### ISSUE TITLE
Homebridge stopped

### ISSUE THREAD

**Issue by djdacore** [ebaauw/homebridge-p1#26]
Hi! When I installed the plugin into Homebridge, and do the settings like:
{
            "name": "P1",
            "serialport": "/dev/ttyUSB0",
            "dsmr22": true,
            "platform": "P1"
        }
and I restart Homebridge, it wont start the service again. When I delete above rules then it will start again. Is there anything to repair this?
Im using a raspberry 3+ and running the homebridge in docker

**Comment by djdacore** [comment]
this is the error I can see in the log:
[1/2/2020, 9:47:36 PM] [eDomoticz] Could not register platform accessory! (Gasverbruik)
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8530a57a-c836-4073-b779-f85eb864e7c2

**Comment by ebaauw** [comment]
Could you please capture a full debug logfile (see https://github.com/ebaauw/homebridge-hue#debug-log-file) and attach that?

**Comment by djdacore** [comment]
{
    "bridge": {
        "name": "Homebridge 8C2B",
        "username": "0E:C9:54:3B:8C:2B",
        "port": 52710,
        "pin": "031-45-154"
    },
    "accessories": [],
    "mqtt": {
        "host": "127.0.0.1",
        "port": 1883,
        "topic": "domoticz/out"
    },
    "platforms": [
        {
            "name": "eDomoticz",
            "server": "*:*@127.0.0.1",
            "port": 9999,
            "roomid": 4,
            "mqtt": true,
            "ssl": false,
            "debuglog": false,
            "dimFix": 0,
            "platform": "eDomoticz"
        },
        {
            "name": "P1",
            "serialport": "/dev/ttyUSB0",
            "platform": "P1"
        }
    ]
}

**Comment by djdacore** [comment]
and also the log file errors:
[1/2/2020, 10:13:22 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 8530a57a-c836-4073-b779-f85eb864e7c2
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:396:18)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)

**Comment by ebaauw** [comment]
This is not helpful, please attach the full debug log file.  I need to see the errors in context.

I don’t think the errors are issued by homebridge-p1.  Did you try to run homebridge with only homebridge-p1 enabled?  Are you exposing your electricity and gas meters from eDomoticz as well?  “Energieverbruik” and “Gasverbruik” are not names used by homebridge-p1.

**Comment by djdacore** [comment]
I've got it running now. I saw a few errors when installing your plugin. I repaired it by doing the following command: npm install --build-from-resource
after that it loaded successfully!

One thing left is that it won't recognize my USB port. it says "[P1] error: Error: No such file or directory, cannot open /dev/ttyUSB0

Im sure its the right port because Domoticz already runs this port with the P1 smart meter cable. Any suggestions?

**Comment by ebaauw** [comment]
Two:
- Is the user running homebridge member of the `dialout` group?
- Only one programme can access the serial port concurrently.  Do you see the same error when Domoticz is not running?  To overcome this, I'm setting up a web socket server in homebridge-p1, to relay the telegrams to other clients, see #5.__

**Comment by ebaauw** [comment]
Oh, you're running homebridge from inside a docker container.  Are you sure the serial port device has been made available to the container.  I'm sorry, but I have no clue how to do that.  While docker is great in the data centre, I think it's not worth the trouble in a home automation setup, where you need access to physical ports and local-link multicast network addresses (for Bonjour and UPnP).

**Comment by djdacore** [comment]
Maybe you are right! I will try to uninstall the homebridge and install everything back without installing in a container. I tried already everything with rights and adding to dialup group but it wont work. I will let you know here if I get it working!

**Comment by ebaauw** [comment]
The did manage to get deCONZ running in a container, it needs access to the USB ZigBee stick.  Maybe that could give you some inspiration?  https://hub.docker.com/r/marthoc/deconz
