### ISSUE TITLE
Permission denied, cannot open /dev/ttyUSB0

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-p1#28]
Due to a crash i had to reinstall homebridge. But after the install of de P1 plugin i get the following error. I did not change anything on the USB part, only installed homebridge (and the plugins).

`Jan 19 15:29:26 RaspberryPi homebridge[19977]: [1/19/2020, 3:29:26 PM] [P1] error: Error: Permission denied, cannot open /dev/ttyUSB0`

**Comment by ebaauw** [comment]
That’s not an issue with homebridge-p1 itself, but with your setup.  Some hints:
- Double-check that the P1 cable is exposed as `/dev/ttyUSB0`.  I use the `@serialport/list` package for that.
- Double-check that the user running homebridge can access `/dev/ttyUSB0`.  It it a member of the `dialout` group?
- Double-check that no other program has opened the port: `lsof /dev/ttyUSB0`.

**Comment by tomsteenbakkers** [comment]
Did was the trick: `sudo adduser homebridge dialout`

Thanks for the support!

**Comment by tomsteenbakkers** [comment]
One more thing: after the reinstall the Energy tile is shown in the Home app and within Eve. But the tile keeps appearing as favorite within the Home app. When I switch the switch off, and reappears every time. Any suggestion to solve this. I do not need the tile in the Home app, only in Eve app

**Comment by ebaauw** [comment]
Not sure.  Favorites are per HomeKit app, but Home shares the state across devices (through iCloud).  Try setting the favorite status off using another device, or from Home on macOS.  Could also be you simply need to wait for the new HomeKit config to be synced across all your devices, before the change will stick.  Might take an hour or so.

**Comment by tomsteenbakkers** [comment]
I figured out that you have to assign the accessories to another room and rename it. If you do not do this than the switch Favorite will not work 

Thanks for the support
