### ISSUE TITLE
Support for solar panel installations?

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-p1#3]
The smart meter reports the electricity delivered back to the network in case you have solar panels.  I don't and homebridge-p1 currently ignored this information.  Technically, it would be possible to expose this to HomeKit, but I'm not sure how best to do this.  Would you want to net the energy consumed vs delivered, or would you want separate accessories for consumption vs delivery?

Please let me know your views.

**Comment by Vaoske** [comment]
I prefer separate accessories for consumption vs delivery.

**Comment by ebaauw** [comment]
That would also enable history for delivery back.

**Comment by Vaoske** [comment]
Works, great!

**Comment by ebaauw** [comment]
Cool.

I cannot test myself, as I don't have solar panels, so may I please ask:
- Can you double-check the reported total consumption (delivered) values in Eve against the meter's display?
- Can you capture and attach another debug logfile, while running `homebridge -D` for an hour or so, so I can double-check that homebridge-p1 behaves like I expect it should?
- After the hour, can you check in Eve that the history is recorded correctly, for the _Electricity_ as well as for the _Electricity Delivered_ service?

Thanks.  If this all checks out, I'll publish a release (non-beta) version.

**Comment by Vaoske** [comment]
Hi,

1) values in Eve the same as on my meter's display
2) [homebridge.log](https://github.com/ebaauw/homebridge-p1/files/2920506/homebridge.log)
3) history recorder correctly

**Comment by ebaauw** [comment]
Thanks very much.  Log looks fine as well.  Just release v2.0.9.
