### ISSUE TITLE
No usable data found

### ISSUE THREAD

**Issue by ditistijn** [ebaauw/homebridge-p1#30]
I just received my P1 cable and connected it to my homebridge server.
When I start it, it says it is connected successfully to /dev/ttyUSB0 but after that throws an error that there is no usable data found. 
I have the Landis & Gyr E350. Is there any additional configuration that I'm missing?
Thanks

**Comment by macdivernl** [comment]
Hi Tijn,

Is your HomeBridge user member of the ‘wheel’ group?

Regards,

Marc

**Comment by ebaauw** [comment]
Does receive data later on?  In that case, set `timeout` in config.json to give Homebridge P1 some more time to capture the first telegram from the meter.

If not:
- Do you have any other USB devices connected?  Are you sure the P1 cable is `/dev/USB0`?
- What DSMR version does your meter use?  Be sure to set `dsmr22` for v2.2, as it needs different communication settings.

**Comment by ditistijn** [comment]
> Hi Tijn,
> 
> Is your HomeBridge user member of the ‘dialout’ group?
> 
> Regards,
> 
> Marc
> 
> See: #28

Thanks for the reply.
The user is part of the dialout group.

**Comment by ditistijn** [comment]
> Does receive data later on? In that case, set `timeout` in config.json to give Homebridge P1 some more time to capture the first telegram from the meter.
> 
> If not:
> 
> * Do you have any other USB devices connected?  Are you sure the P1 cable is `/dev/USB0`?
> * What DSMR version does your meter use?  Be sure to set `dsmr22` for v2.2, as it needs different communication settings.

Hi,
Thanks for the reply.
I am running on an orange pi zero so the cable is connected to the only usb port available.
The meter says it uses DSMR 4.2.

For some reason I can't get any signal from the cable. When I connect it to my windows laptop and open the serial port via putty it also won't receive any signal. Baud rate is set to 115200.

Thanks!

**Comment by ebaauw** [comment]
DSMR 4.2 probably only sends a telegram per 10 seconds, so setting `timeout` to 50 would be prudent.

Afaik, the serial settings should be 115200 8N1, except for DSMR 2.2, where it's 9600 7E1.  I understand that the P1 module in the meter actually needs to detect that the cable is connected, before sending anything.  Better double-check the cable.  Did you solder it yourself, or did you buy it somewhere?

**Comment by ditistijn** [comment]
I set the timeout to 50. Still no sign of life.
How can I set the 8N1 thingy in putty? Or is that not necessary?
I bought it off AliExpress for a couple of euros. I am in contact with the supplier right now, hoping to find a resolution.
In the FTDI software it said that it was already flashed with Rx inverted so that can't be the problem right? Can it possibly be the pinout?  
Thanks!

**Comment by ebaauw** [comment]
Sorry, don't know `putty`.

See the link in the README for details on the cable.  I have no other info.  Note: that page seems to suggest that DSMR 4.2 uses 115200 7E1, but in other cases (#17, #7), the 8N1 setting seemed to work fine.

I have no experience with other cables than the one I ordered from SOS Solutions (link in README).

**Comment by ditistijn** [comment]
I bought the SOS Solutions cable, set the timeout to 30 and it just worked! Great plugin!
Do you happen to know how I can change the tariff in Eve?
Thanks?

**Comment by ebaauw** [comment]
> Do you happen to know how I can change the tariff in Eve?

Settings | General | Energy Cost.  I suppose it only displays this option when it sees Eve Energy-like devices.
