### ISSUE TITLE
add option to suppress logging of meter readings

### ISSUE THREAD

**Issue by stannie** [ebaauw/homebridge-p1#32]
v0.2.42 and earlier, at least when installed via the Homebridge UI, log all meter readings / telegrams which push logs from other plugins off screen quite quickly. 
Would be convenient if the regular / expected messages could be suppressed, possibly even have this off by default.

**Comment by ebaauw** [comment]
I plan to do that when refactoring Homebridge P1 to use the dynamic platform accessory model.  Sorry, no ETA yet.

**Comment by ebaauw** [comment]
In v1.0.0 there's an extra characteristic _Log Level_ to configure the amount of logging by Homebridge P1, see https://github.com/ebaauw/homebridge-lib/issues/26.
