### ISSUE TITLE
Resource temporarly unvailable error

### ISSUE THREAD

**Issue by jeroen020** [ebaauw/homebridge-p1#37]
Since a couple of days I can no longer access the P1 in HomeBridge running on my Raspberry Pi 4 - the log shows the following error:

[P1] warning: Error Resource temporarily unavailable Cannot lock port

I've checked and it's configured correctly in config.js (on /dev/ttyUSB1). Also my Youless, when connected to the smart meter, works as expected. I've got a Enocean stick on USB0. 

Any idea what else I can try to access the P1 again?

**Comment by ebaauw** [comment]
It seems to be an error connecting to the serial port provided by the P1 cable. Most likely another program is already using the port.  Did you install any new software or hardware before the error appeared?

I assume you tried unplugging the cable, from the Pi as well as from the meter and rebooting the Pi?
