### ISSUE TITLE
Homekit accesorry not showing data

### ISSUE THREAD

**Issue by r67tam** [ebaauw/homebridge-p1#40]
I can see data is comminig in the Homebridge status (main screen)
The plugin created two accessoires bus there is no data. 
The accessoires only showing "Niet Geschikt" not compatible. 

![image](https://user-images.githubusercontent.com/72225272/95665094-5f0ce500-0b4d-11eb-97c0-d12037a950b1.jpeg)

![image](https://user-images.githubusercontent.com/72225272/95665169-02f69080-0b4e-11eb-9e6c-24b145eb28b6.jpeg)

**Comment by ebaauw** [comment]
See the README: Apple’s Home app doesn’t support all of HomeKit.  You need to use another HomeKit app, like Eve.

**Comment by r67tam** [comment]
Oké thanks
I am a poor english reader

Thanks for the info
