### ISSUE TITLE
Can not remove P1 accessory from favorites in Home app

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-p1#41]
After the iOS14 upgrade I discovered something weird. The P1 is added to the Home App as an unsupported accessory. So far nothing new. But is stays in my Favorites. There is no option on the accessory page to remove this.

Any idea how to solve this?

![image](https://user-images.githubusercontent.com/24613800/97115518-5db7ec80-16f7-11eb-9562-b9b5d1611ab8.jpeg)

**Comment by ebaauw** [comment]
Somehow Home on iOS14 no longer provides favourite settings for unsupported accessories.  You can still change this setting on Home on macOS or on iOS13.

The only thing I can do is expose the meters as something that Home recognises, e.g. a non-functional switch or outlet.

**Comment by tomsteenbakkers** [comment]
Ok, for now I will change the setting on Mac OS.

**Comment by gerbenvandijk** [comment]
This option has also disapeared now on the latest MacOs, can I help with exposing this differently?

**Comment by ebaauw** [comment]
Big Sur?  That was to be expected.

Apparently an accessory now needs at least one supported service to be unmarked as favourite.  I fail to understand Apple’s reasoning here.  I tried a read-only _Switch_ before, but Home doesn’t accept that either.  I was thinking maybe to use a _Stateless Programmable Switch_, but that makes no sense semantically.

**Comment by gerbenvandijk** [comment]
That indeed doesn't make much sense; but from the user perspective it would be good because the goal is to _hide_ them from the favourites screen. A dummy but supported switch to achieve that goal imho is for now perhaps the best possible way?

**Comment by ebaauw** [comment]
It's what I did for the bridge/gateway accessory in Homebridge Hue.

**Comment by ebaauw** [comment]
In v1.1.3.

**Comment by rhvs** [comment]
> In v1.1.3.

Updated everything but no change here

**Comment by ebaauw** [comment]
Did you set `button` in config.json?

**Comment by rhvs** [comment]
> Did you set `button` in config.json?

I guess I was a bit impatient... it works! Thanks!
