### ISSUE TITLE
Wrong totals in Eve Home app

### ISSUE THREAD

**Issue by muratcorlu** [ebaauw/homebridge-p1#42]
Firstly thanks for this great effort. I use this plugin and meter readings are correct in Eve Home app but somehow daily totals are way less than actual values. I spend 10kwh per day in average but in Eve home app I see around 2-3 at most. What can be the cause?

![image](https://user-images.githubusercontent.com/127687/97778036-adbe0580-1b74-11eb-84d8-a5ed590e1377.jpeg)

**Comment by ebaauw** [comment]
I have no clue how this can be happening.  Homebridge P1 writes a history entry every 10 minutes, computing the consumption from the difference in _Total Consumption_.  Even if Homebridge P1 doesn’t run for a while, the next entry should make up the difference.

Do you see 144 measurements per day?

**Comment by muratcorlu** [comment]
Yes, mostly I see 144 records per day. 
![image](https://user-images.githubusercontent.com/127687/97787217-29d63e80-1bb1-11eb-942f-bd6b45345974.png)
![image](https://user-images.githubusercontent.com/127687/97787224-30fd4c80-1bb1-11eb-8d76-a7f63b3ee804.png)

I thought maybe difference also being sent from plug-in. But if this plugin only sends latest reading than issue should be on the application side, I think.

**Comment by thomas-svrts** [comment]
Hi Erik,

I notice the same, history is not correct in Eve. Maybe an issue in hex/base64 encoding?

see next example:
<img src="https://user-images.githubusercontent.com/81048302/112155970-1ec68e00-8be6-11eb-9881-bb461cf3e9d7.PNG" width="50%"/>

app is showing :
- 13:13 ==> 66,83 Wh in Eve, homebridge-p1 calculates 401Wh
- 13:23 ==> 42 Wh in Eve, homebridge-p1 calculates 252Wh
- 13:33 ==> 39,67 Wh in Eve, homebridge-p1 calculated 238Wh

```
23/3/2021 13:13:43] [P1] Electricity Delivered History: add entry 298: {"time":1616501623,"power":401}
[23/3/2021 13:13:43] [P1] Electricity Delivered History: set history status to: f9ab0200 00000000 fe660726 [01 0702] 2b01 c00f 00000000 000000000101
[23/3/2021 13:13:43] [P1] Electricity Delivered History: set History Status from "oakCAAAAAAD+ZgcmAQcCKgHADwAAAAAAAAAAAQE=" to "+asCAAAAAAD+ZgcmAQcCKwHADwAAAAAAAAAAAQE="
[23/3/2021 13:13:43] [P1] Electricity Delivered History: set consumption from 2643.643 to 2644.044
[23/3/2021 13:13:43] [P1] Electricity Delivered: set Total Consumption from 2644.044 kWh to 2644.045 kWh
[23/3/2021 13:13:50] [P1] Electricity Delivered: set Total Consumption from 2644.048 kWh to 2644.049 kWh
[23/3/2021 13:23:38] [P1] Electricity Delivered: set Total Consumption from 2644.294 kWh to 2644.295 kWh
[23/3/2021 13:23:42] [P1] Electricity Delivered: set Total Consumption from 2644.295 kWh to 2644.296 kWh
[23/3/2021 13:23:43] [P1] Electricity Delivered History: add entry 299: {"time":1616502223,"power":252}
[23/3/2021 13:23:43] [P1] Electricity Delivered History: set history status to: 51ae0200 00000000 fe660726 [01 0702] 2c01 c00f 00000000 000000000101
[23/3/2021 13:23:43] [P1] Electricity Delivered History: set History Status from "+asCAAAAAAD+ZgcmAQcCKwHADwAAAAAAAAAAAQE=" to "Ua4CAAAAAAD+ZgcmAQcCLAHADwAAAAAAAAAAAQE="
[23/3/2021 13:23:43] [P1] Electricity Delivered History: set consumption from 2644.044 to 2644.296
...
[23/3/2021 13:33:43] [P1] Electricity Delivered History: add entry 300: {"time":1616502823,"power":238}
[23/3/2021 13:43:43] [P1] Electricity Delivered History: add entry 301: {"time":1616503423,"power":258}
```

**Comment by thomas-svrts** [comment]
According to https://github.com/simont77/fakegato-history

Add entries to history of accessory emulating **Eve Energy** (Outlet service) using something like this:

  this.loggingService.addEntry({time: Math.round(new Date().valueOf() / 1000), power: this.power});
Power is in Watt. **Entries are internally averaged** and sent every 10 minutes using the global fakegato timer. To have good accuracy, your entries should be in any case periodic, in order to avoid error with the average

==> so if you supply each 10 minutes a history you should multiply your Wh by 6 (6 times 10 minutes in 1 hour)
Eve will internally average it again. **So you should provide the consumption of 1 equivalent hour.**

**Comment by ebaauw** [comment]
When creating a history entry, Homebridge P1 computes the difference between the current total consumption and the total consumption at the time of the previous history entry.  That's the consumption in kWh over the last 10 minutes.  It then multiplies this by 6000 to get the average power during those 10 minutes in W. This is the entry sent to Eve (and shown in the log).  Eve then computes the consumption in Wh by dividing this value by 6.  Those are the values shown in Eve.

**Comment by thomas-svrts** [comment]
Just a small remark: sometime the delta is not 10 minutes. So in those cases it will still be wrong, but not with a factor 6 ;-).

![E7503B18-81F5-4C43-AE29-0C6E36E387A3](https://user-images.githubusercontent.com/81048302/112190392-3e20e380-8c05-11eb-9606-66a860521588.jpeg)

**Comment by ebaauw** [comment]
> Just a small remark: sometime the delta is not 10 minutes

That should only happen when you restart Homebridge.

> So in those cases it will still be wrong, but not with a factor 6

I think I can persist the time of the previous log entry and compute the average power by dividing the consumption difference by the time difference.  Not sure how well Eve would handle that.  On a real Eve Energy, entries would only be missing when the plug is not connected to mains.  In that case, consumption stops.  However, when Homebridge is down, consumption continues.

**Comment by ebaauw** [comment]
Could you try beta v1.2.1-1?

**Comment by thomas-svrts** [comment]
Hmm tried it quickly… but not receiving history anymore.

![715A74A2-F6EC-4701-BC33-9D04845B55E7](https://user-images.githubusercontent.com/81048302/112719397-1a0d1d00-8ef9-11eb-8f23-179837afd9c7.jpeg)


logs will follow…

**Comment by ebaauw** [comment]
> but not receiving history the 1st time after reboot.

Because the time of the previous entry is not yet available.  Should be OK on subsequent reboots.  Not sure why I only comes after 20 minutes; I would expect 10 minutes...

**Comment by thomas-svrts** [comment]
Yeah, you’re right. It only happened the first time.
Sounds fixed for me.

**Comment by ebaauw** [comment]
Release v1.2.1.
