### ISSUE TITLE
Get no data from P1

### ISSUE THREAD

**Issue by githubhash** [ebaauw/homebridge-p1#45]
Hello,

This is the situation:

- Brand new install of Homebridge on Raspberry Pi 4B with the official image
- Install of the P1 plugin using the UI
- Connected to the ISKRA AM550 using this cable: https://www.tinytronics.nl/shop/nl/communicatie/serieel/ft232-3.3-5v-ttl-usb-serial-port-adapter-met-kabel and this one: https://www.tinytronics.nl/shop/nl/kabels/adapters/rj12-naar-6-pins-dupont-jumper-adapter
- Getting these messages and no accessoires in Homekit or Homebridge:
[02/02/2021, 20:06:42] [P1] connected to /dev/ttyUSB0
[02/02/2021, 20:06:47] [P1] warning: no data received in 5s
[02/02/2021, 20:06:47] [P1] disconnected from /dev/ttyUSB0

What's going wrong and how can I fix it? Any help is appreciated!

**Comment by ebaauw** [comment]
Where you able to get data with those cables using other programme?  The P1 interface uses a funny pin assignment, and needs a resistor between TX and RTX, see link in the README.  It will only start sending data when it detects a connection.

What DSMR does your meter provide.  You might need to set the appropriate config.json parameters: `dsmr22` or `timeout`, see README.

**Comment by githubhash** [comment]
The ISKRA AM550 is an SMR 5.0 meter. Do you have an suggestion for testing with other programs? Currently I'm investigating the pin assignment, wondering where the Data GND must be connected to at this cable https://www.tinytronics.nl/shop/nl/communicatie/serieel/ft232-3.3-5v-ttl-usb-serial-port-adapter-met-kabel

I connected the:
pin1 to 5V (red cable on USB)
pin2 to RTS (yellow cable on USB)
pin3 to ???
pin4 not connected
pin5 to RX (white cable on USB)
pin6 to GND (black cable on USB)

**Comment by ebaauw** [comment]
The P1 USB cable is a serial port.  You just plug it into one of the Pi’s USB ports.  The other end goes into the meter.  It doesn’t use any GPIO pins.  See the link in the README.  There’s also an example to use `cu` to test the connection to the meter.

**Comment by githubhash** [comment]
Because the USB cable has 1 pin for ground, I decided to connect pin6 on the RJ12 to the ground cable on the USB side and connected the pin3 on the RJ12 (Data GND) to the GND on the GPIO. 

With the FT_PROG I inverted the RXD signal, no result. I can connect using cu in the terminal, the message says "Connected.", but no telegram is received.

**Comment by ebaauw** [comment]
If you don't get any telegram in `cu`, there's probably an issue with the cable or with the way you wired it.  I'm sorry, but I cannot help you with that.

**Comment by githubhash** [comment]
Thanks for your directions, I contact the supplier of the cable to troubleshoot.

**Comment by githubhash** [comment]
It was a problem with the cable. I ordered a new one and it works without issues. Thanks again for your help!
