### ISSUE TITLE
homebridge-p1 blocks P1 interface for other uses

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-p1#5]
Currently, homebridge-p1 keeps a permanent, exclusive connection to the serial port connected to the P1 port.  While this works great for HomeKit-only scenarios, you cannot use another data logger or run multiple instances of homebridge-p1 in parallel (e.g. testing a new version).

I might need to split off the P1 client from homebridge-p1 into a separate interfacing service.  This service would provide a web socket server.  It would connect to the serial port and simply re-broadcast every telegram over the web socket.  homebridge-p1 (and other clients) would then read the telegrams from the web socket instead of form the serial port.

Of course doing this would complicate the installation of homebridge-p1.

**Comment by QempZor** [comment]
This seems like a very nice plugin.
Going to test it this weekend.

How ever, i'm currently running Homebridge and DeCONZ gateway on the same raspberry.
Is it still possible with this addon? 
The Raspbee interface uses /dev/ttyS0.

**Comment by ebaauw** [comment]
I’m running deCONZ, homebridge-hue, and homebridge-p1 on a single Raspberry Pi 3B+ with a RaspBee.

**Comment by macdivernl** [comment]
Hi there!

My electricity connection, so also 'Smart Meter' supports three phases.
Have you considered the possibility to specify if you've got L1 L2 L3 etc?

Thanks!

Marc

**Comment by ebaauw** [comment]
v0.2.32 includes a web socket server to re-broadcast the telegrams read from the P1.  Set `"wsPort": 8088` (or use your favourite port) in config.json to activate it.

I have a simple web socket client in `test/ctest.js`.  Next on my todo list is to make homebridge-p1 connect to the web socket instead of to the serial port.  And to create a simple command-line tool (that can be run as a service) to connect to the serial port and offer the web socket server.  I envision this tool to run on the host system, when homebridge runs in a container, so you don't have to go through the trouble of exposing the USB serial port to the container.

**Comment by jeroen020** [comment]
Thanks for your great work, also a big fan of homebridge-hue. Just getting started with the p1 plugin. For quite some time already I use a [Youless](https://www.youless.nl/home.html) LS120 which also needs the P1 port. Today I received my P1 USB cable and a [splitter](https://webshop.cedel.nl/P1-Kabel-Splitter) with master and slave outputs. Tested it today with my meter (AM550-TD2.01, 3 phases). I can only get it to work if I plug it directly into the meter or if it's the the only output in the splitter. As soon as I plug in the Youless in either the master or slave port next to the USB cable, log entries for homebridge-p1 stop and eventually time out error occurs.

My question: I noticed there are different types of splitters; this one seems to be different as it is active and regenerates the data line. Do you think this active splitter would work?

Another thought/suggestion - if you could get data from the Youless in the plugin as a source, that would be great. Let me know if I can help in any way.

**Comment by ebaauw** [comment]
> As soon as I plug in the Youless in either the master or slave port next to the USB cable, log entries for homebridge-p1 stop and eventually time out error occurs.

Do the log entries to the Youless continue?  As I understand, the meter only sends telegrams when it detects something connected to the P1 port.  Maybe the splitter sends the wrong signal to the meter when two devices are connected?  Or maybe the split signal is too weak for the USB cable to pick up?

> Do you think this active splitter would work?

I have no idea.

> if you could get data from the Youless in the plugin as a source

How does the Youless relay the data?  If it sends the raw telegrams over a web socket I can probably make it work.  Any other way would probably be too much work.

**Comment by jeroen020** [comment]
> Do the log entries to the Youless continue? As I understand, the meter only sends telegrams when it detects something connected to the P1 port. Maybe the splitter sends the wrong signal to the meter when two devices are connected? Or maybe the split signal is too weak for the USB cable to pick up?

Not sure what is happening. I tried again, and if the USB cable is the only one in the P1 splitter, it works; as soon as I add the the Youless, homebridge-p1 stops getting data. If I unplug the Youless, it starts receiving them again. 

> How does the Youless relay the data? If it sends the raw telegrams over a web socket I can probably make it work. Any other way would probably be too much work.

I tried to find out more but can't see any mention of websockets in the context of the Youless; I do use it with a Homey as well as Enelogic (online energy dashboard).

**Comment by jeroen020** [comment]
Update, I exchanged the passive splitter for an [active one](https://www.tech4ushop.nl/p1-splitter-4x.html) and now I am able to use the USB cable for Homebridge and the Youless LS 120 simultaneously.

**Comment by sebastiaan88** [comment]
Hi Erik,

Since theres no "Energy Monitor" (yet) in homekit to display on iOS devices, I thought maybe we could spoof it by using a temperature or luminance sensor to show current usage kWh / gas m3 from the P1 data? I know the suffix would be wrong (F/C or lux) but who cares, at least we can see usage on iPhone. Would you know how to connect this data to a fake sensor?

**Comment by ebaauw** [comment]
Have you tried the Eve app?  It shows the history of electricity and gas consumption by homebridge-p1.

**Comment by sebastiaan88** [comment]
> Have you tried the Eve app? It shows the history of electricity and gas consumption by homebridge-p1.

Yes that works but I was hoping when creating a fake sensor using the p1 data somehow and have it active in homebridge I would be able to also see it on my Home app thus also on the Apple Watch. You get te idea? Think its possible?

**Comment by ebaauw** [comment]
Technically, yes.

You would need a homebridge plugin that connects to homebridge-p1's web socket and exposes a temperature sensor.  Technically, a homebridge plugin can expose a device using any type of HomeKit accessory, services, and characteristics.  For example, homebridge-zp exposes Sonos zone players as _Television_, so you can select the input in Apple's Home app, and control them through the _Remote_ widget.

Rather than connecting to the P1 itself, the plugin would re-use the parsed P1 data from homebridge-p1's web socket.  See https://github.com/ebaauw/homebridge-p1/blob/master/test/ctest.js for a very simple example programme that logs the data to the console.

I would probably need to provide some more documentation for `P1WsClient`.  Also, I need to add it to the exports, or maybe expose it as a separate library, so others can `require` it.

**Comment by ebaauw** [comment]
v1.0.0 has an (as yet undocumented) config.json setting `host` which specifies the hostname:port of a websocket server exposed by Homebridge P1, with `wsPort` set.

**Comment by tomsteenbakkers** [comment]
Hi Erik,

Small questions: I have p1 running on the RaspberryPi and it's working fine. I see the graphs in the Eve app. The only thing is that interacting with these graphs is very limited in the Eve app. 

I have installed https://github.com/psy0rz/p1_dsmr_to_influxdb. This python script gets the data from the p1 port and insert them in an Influx DB so I can use Grafana to make nice dashboard to interact with the data.

As you mentioned your plugin keeps a permanent, exclusive connection to the serial port which means that the Python script can not access the P1 port when Homebridge is running. If I stop Homebridge the script is filling up the Influx DB.

It is an option that, besides sending the data to the Eve app, you also can send the data to an Influx Database.

Thanks for you response in advance.
