### ISSUE TITLE
3 Phase P1 Meter not showing individual phases in Eve-app

### ISSUE THREAD

**Issue by remmie1972** [ebaauw/homebridge-p1#59]
Hi Erik,

Thanks for an awesome plugin ! However I'am having a little trouble with it. 
In the closed issues there is a topic about 3 phase P1 meters. I have a 3 phase installation and the Eve app only shows a single current value, not split into L1, L2 and L3. Could it be a setting?  the config of the homebridge P1-plugin is below :

{
            "dsmr22": false,
            "name": "P1",
            "outlet": false,
            "serialPort": "/dev/ttyUSB0",
            "timeout": 60,
            "platform": "P1"
 },

Also in the closed topic you requested a log of homebridge running in debug mode (-D). hereby that log : 
in the log I can make out the separate currents and powers for all 3 phases. But still the Eve app does not show all 3, just a single current/power. For information : I also have solar panels so the power back values will be used. I guess that is obvious from consumption back T1 and T2 values in the log though :)

[08/01/2022, 00:02:59] [P1] raw data: 
{"type":"KFM5KAIFA-METER",
"checksum":"EF9E",
"version":"4.2",
"lastupdated":"2022-01-08T00:02:26",
"id":"E0026000030985316",
"consumption_t1":24575.366,
"consumption_t2":13445.403,
"consumption_back_t1":5595.177,
"consumption_back_t2":14397.615,
"tariff":1,
"power":712,
"power_back":0,
"failures_short":3,
"failures_long":1,
"log":{"2017-03-26T04:38:04":11313,"2000-01-01T00:00:01":2147483647},
"l1_sags":0,
"l2_sags":1,
"l3_sags":1,
"l1_swells":0,
"l2_swells":0,
"l3_swells":0,
"msg_num":"",
"msg_text":"",
"l1_current":2,
"l2_current":0,
"l3_current":1,
"l1_power":400,
"l2_power":127,
"l3_power":194,
"l1_power_back":0,
"l2_power_back":0,
"l3_power_back":0
}

[08/01/2022, 00:02:59] [P1] telegram:
KFM5KAIFA-METER

1-3:0.2.8(42)
0-0:1.0.0(220108000226W)
0-0:96.1.1(4530303236303030303330393835333136)
1-0:1.8.1(024575.366*kWh)
1-0:1.8.2(013445.403*kWh)
1-0:2.8.1(005595.177*kWh)
1-0:2.8.2(014397.615*kWh)
0-0:96.14.0(0001)
1-0:1.7.0(00.712*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00003)
0-0:96.7.9(00001)
1-0:99.97.0(2)(0-0:96.7.19)(170326043804S)(0000011313*s)(000101000001W)(2147483647*s)
1-0:32.32.0(00000)
1-0:52.32.0(00001)
1-0:72.32.0(00001)
1-0:32.36.0(00000)
1-0:52.36.0(00000)
1-0:72.36.0(00000)
0-0:96.13.1()
0-0:96.13.0()
1-0:31.7.0(002*A)
1-0:51.7.0(000*A)
1-0:71.7.0(001*A)
1-0:21.7.0(00.400*kW)
1-0:41.7.0(00.127*kW)
1-0:61.7.0(00.194*kW)
1-0:22.7.0(00.000*kW)
1-0:42.7.0(00.000*kW)
1-0:62.7.0(00.000*kW)
!EF9E

**Comment by ebaauw** [comment]
Next time, please attach a log file.  Copy/pasting mutilates the telegram.

The parser for telegrams looks at voltage per phase, to determine whether the meter is reporting 3-phase electricity.  However, DSMR 4.2 isn't reporting voltage.  I'll change the parser to check to power instead.

**Comment by remmie1972** [comment]
Hi Erik, 

Thanks for the update! All 3 phases show up now. Great stuff!
