### ISSUE TITLE
Use Ztatz P1-monitor tot connect to smart meter

### ISSUE THREAD

**Issue by SterkeYerke** [ebaauw/homebridge-p1#65]
Homebridge P1 now works with a direct serial connection to the smart meter. Would it be possible to use an indirect approach using Ztatz P1-monitor on a separate raspberry pi? 

P1-monitor can take care of all the historical archiving and HomeBridge / HomeKit  can be used to display gauges of current usage and trigger automations.

P1-monitor has simple API that returns current power and or gas usage. 

Happy to help with testing if needed.

**Comment by ebaauw** [comment]
That's technically possible, I suppose, but supporting a different protocol is beyond the scope of Homebridge P1.

You can use `ser2net` to access the serial protocol over the network.
