### ISSUE TITLE
The necessity for a USB-cable

### ISSUE THREAD

**Issue by gopniq** [ebaauw/homebridge-p1#68]
I was wondering why there’s the necessity to connect the P1 with a USB cable because on modern meters the P1 can draw its power from the other connection. Also in HA it works without having a USB cable connected. Is there a possibility around this? Because I’m not really willing to plug in a USB cable just for the sake of having it visible in HomeKit.

**Comment by ebaauw** [comment]
I suppose you could connect the P1 port to any serial interface, if your system still has one.  The P1 USB cable is just a USB to serial cable dealing with the weird pin layout of the P1 port.  It doesn’t power the port, but connects one of the data wires over a resistor to power, to activate the port.  See the link in the README for details.
