### ISSUE TITLE
USB cable not found

### ISSUE THREAD

**Issue by tomsteenbakkers** [ebaauw/homebridge-p1#7]
I have bought a P1 cable, attached it to the RaspberryPi and installed the software. After the software successfully is installed I rebooted the RaspberryPi. During the boot of Homebridge I see that the P1 software is loaded, with 2 warnings about the node version and the Homebridge version. 

```
[2018-5-7 20:59:58] [P1] Initializing P1 platform...
[2018-5-7 20:59:58] [P1] homebridge-p1 v0.0.2, node v10.0.0, homebridge v0.4.42
[2018-5-7 20:59:58] [P1] warning: not using recommended node version v8.9.4 LTS
[2018-5-7 20:59:58] [P1] warning: not using recommended homebridge version v0.4.38
```
After this I get the error that the usb cable is not found. 
`[2018-5-7 21:00:00] [P1] P1 USB cable not found`

I checked the usb devices with lsusb and I see the usb device

`Bus 001 Device 004: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port`

All other plugins are working properly (also the Philips Hue plugin of ebaauw 😇)

Any ideas how to solve this?

**Comment by ebaauw** [comment]
Can you please run `serialport-list` and copy the output here?  Your cable might have a different serial-to-USB chip, which identifies itself differently.  Using `lsusb`, mine reports:
```
Bus 001 Device 004: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
```
and `serialport-list` reports
```
/dev/ttyUSB0	usb-FTDI_P1_Converter_Cable_P12DB9CI-if00-port0	FTDI
```

**Comment by ebaauw** [comment]
@tomsteenbakkers, could you try v0.1.2?   That version should recognise your cable.
```
$ sudo npm -g un homebridge-p1
$ sudo npm -g i homebridge-p1 --unsafe-perm
```
Could you please run `homebridge -D` and copy the `[P1]` lines here?  I'm particularly interested in the debug lines for ports, telegram, and data.  What brand and model of meter do you have?

**Comment by tomsteenbakkers** [comment]
@ebaauw I have installed the new version. Reboot the Pi and run homebridge in debug mode (not using systemd).

It look like he can find the cable, but when I run homebridge using systemd I get an error that he can not open the USB port. How can I solve this, because using starting homebridge from the command line does not work.


This is the log for [P1]

```
[2018-5-8 12:55:16] [P1] Initializing P1 platform...
[2018-5-8 12:55:16] [P1] homebridge-p1 v0.1.2, node v10.0.0, homebridge v0.4.42
2018-5-8 12:55:18] [P1] ports: [{"comName":"/dev/ttyAMA0"},{"manufacturer":"Prolific Technology Inc.","pnpId":"usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0","vendorId":"067b","productId":"2303","comName":"/dev/ttyUSB0"}]
[2018-5-8 12:55:18] [P1] listening on /dev/ttyUSB0
[2018-5-8 12:55:31] [P1] telegram:
/XMX5LGBBFFB231110695

1-3:0.2.8(42)
0-0:1.0.0(180508125516S)
0-0:96.1.1(4530303034303031353535383131313134)
1-0:1.8.1(008628.469*kWh)
1-0:2.8.1(000000.000*kWh)
1-0:1.8.2(011869.947*kWh)
1-0:2.8.2(000000.000*kWh)
0-0:96.14.0(0002)
1-0:1.7.0(00.337*kW)
1-0:2.7.0(00.000*kW)
0-0:96.7.21(00004)
0-0:96.7.9(00003)
1-0:99.97.0(3)(0-0:96.7.19)(160706161146S)(0007771158*s)(160407173258S)(0041331325*s)(160213220714W)(0000010998*s)
1-0:32.32.0(00000)
1-0:32.36.0(00000)
0-0:96.13.1()
0-0:96.13.0()
1-0:31.7.0(002*A)
1-0:21.7.0(00.337*kW)
1-0:22.7.0(00.000*kW)
!19FE

[2018-5-8 12:55:31] [P1] data: {"type":"XMX5LGBBFFB231110695","version":"4.2","text":null,"electricity":{"id":"E0004001555811114","lastupdated":"2018-05-08T12:55:16+02:00","tariff":"normal","consumption":{"low":8628.469,"normal":11869.947},"power":337,"failures":{"short"$
[2018-5-8 12:55:31] [P1] XMX5LGBBFFB231110695 v4.2
[2018-5-8 12:55:31] [P1] Initializing platform accessory 'Electricity'...
```

**Comment by ebaauw** [comment]
> It look like he can find the cable
> This is the log for [P1]

This is looking good.  It's an older DSMR version (4.2), but homebridge-p1 seems to parse the telegram allright, and it's creating an accessory for _Electricity_.  Doesn't look like you've got a gas meter paired to the electricity meter?  
I haven't seen label `0-0:96.13.1` before, but there's no data for it, so it's probably safe to ignore it.  `0-0:96.13.0` is for text messages (from the electricity network to the meter, I suppose), but it's empty for me as well.

> but when I run homebridge using systemd I get an error that he can not open the USB port. 

Did you stop the homebridge you started manually?  Only one process at a time can access the port.  

What user do you run the service under?  It needs permission to open the device file.  I run the service under user `pi`, using the following `/etc/systemd/system/homebridge.service`:
```
[Unit]
Description=homebridge
After=syslog.target network-online.target

[Service]
Type=simple
User=pi
EnvironmentFile=/etc/default/homebridge
ExecStart=/usr/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
```
and `/etc/defaults/homebridge`:
```
# Command line parameters for homebridge.
HOMEBRIDGE_OPTS=

# Log HAP requests between HomeKit and homebridge.
# DEBUG=*

# Partly shut up the Avahi warnings.
AVAHI_COMPAT_NOWARN=1
```

**Comment by tomsteenbakkers** [comment]
@ebaauw 
My version of `/etc/systemd/system/homebridge.service` is the same, only I start homebridge with the user `homebridge`. 

I have change this to user `pi` and modified the security on the `persist` directory. It is working now.

Is there a simple solution how to start the systemd with user homebridge so this user can read the USB?

![img_6c0a1f72d4df-1](https://user-images.githubusercontent.com/24613800/39755776-699a96c0-52c7-11e8-85b0-4919a89b093a.jpeg)

**Comment by ebaauw** [comment]
Looks like your meter doesn't report voltage.  homebridge-p1 shouldn't create a _Voltage_ characteristic in that case.

> Is there a simple solution how to start the systemd with user homebridge so this user can read the USB?

I'm not sure which group is used for that.  Probably easiest to add user `homebridge` to the same groups as user `pi`:
```
$ sudo usermod homebridge -G adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi
```
If that works, you might want to remove the superfluous groups by trial and error (I'm pretty sure `sudo` isn't needed).

**Comment by tomsteenbakkers** [comment]
@ebaauw Just some extra information: I have only electricity and no gas. Instead I have w 'stadsverwarming'. I do not know if this information is send to the smart meter.

**Comment by tomsteenbakkers** [comment]
I will leave this now for a while to see if it stays stable. After that I will try to set it back to the user `homebridge`.

Thanks for the support, and if you need somebody to test new homebridge plugin's, please let me know: happy to help you!

Maybe off topic: does the current iOS 11.3 version support the speaker services already?

**Comment by ebaauw** [comment]
> Instead I have w 'stadsverwarming'. I do not know if this information is send to the smart meter.

Technically, the DSMR standard could support it, similar to a gas meter.  Looking at the telegram, your meter doesn’t.

> if you need somebody to test new homebridge plugin's, please let me know: happy to help you!

Thanks.  I spent too much time on my plugins already to be creating new ones, but I’m happy to receive any feedback on my current plugins.

> does the current iOS 11.3 version support the speaker services already?

Apple’s Home app has been supporting _Speaker_ for video door bells for ages, but not for other usages.  Airplay 2 doesn’t use HAP, so the speaker Apple’s Home app shows have nothing to do with the _Speaker_ service.  See my homebridge-zp or homebridge-music plugins for details.
