### ISSUE TITLE
👏 `homebridge-p1`-generated charts closely match those of `mijn.fluvius.be`!

### ISSUE THREAD

**Issue by wimleers** [ebaauw/homebridge-p1#73]
## Electricity: 🥳
![IMG_AE7CCC0805D4-1](https://user-images.githubusercontent.com/14240/221032659-70f29f65-3ac5-46aa-8f82-2c17966e377b.jpeg)
vs
<img width="1526" alt="Screenshot 2023-02-23 at 22 18 57" src="https://user-images.githubusercontent.com/14240/221032705-06e70be8-4a88-41be-a2b1-661188275f56.png">

⇒ minimal differences, despite the many cumulative rounding errors! ⇒ very usable :)

## Gas: 😳

![IMG_C365D81FBC68-1](https://user-images.githubusercontent.com/14240/221033181-2c7ca657-7b11-4076-a121-baae2fe99ba2.jpeg)
vs
<img width="1533" alt="Screenshot 2023-02-23 at 22 21 42" src="https://user-images.githubusercontent.com/14240/221033217-b64212cb-cbd0-4c86-84d4-94bb4133ac06.png">

⇒ does not match _at all_, but it's because Fluvius made the completely absurd/idiotic decision to not start the day at midnight, but at 6 AM. So it's 6 AM to 6 AM … 🙃🤷‍♂️

The fact that it's _so close_ for electricity makes me want to trust `homebridge-P1`'s-powered-Eve-charts to read the data Fluvius doesn't offer me! 😊

## Conclusion

_Thank you!_ 😊 

The irony is that `homebridge-p1`-generated charts are _instantaneous_, those at `mijn.fluvius.be` often lag _days_ behind!

_Nothing to do here, just expressing gratitude & admiration!_

**Comment by ebaauw** [comment]
Thanks
