### ISSUE TITLE
1.8.1 Normal 1.8.2 low numbers don't seem correct on Flemish Meter

### ISSUE THREAD

**Issue by Tangheta** [ebaauw/homebridge-p1#74]
Great plugin! 
Worked out of the box on my Flemish meter!

The only minor thing that looks slightly off is the day and night totals.
Flemish meters have 4 counters:
- 1.8.1 Dag Afname
- 1.8.2 Nacht Afname
- 2.8.1 Dag Injectie
- 2.8.2 Nacht Injectie
The numbers in the Eve app don't seem to correspond with these.

**Comment by ebaauw** [comment]
Strictly speaking, 1.8.1 and 2.8.1 are tariff 1; and 1.8.2 and 2.8.2 are tariff 2.  In the Netherlands, tariff 1 is low (night), and tariff 2 is normal (day).  I understand in Flandres, it’s the other way round.



What do you mean the numbers don't correspond?
- Are they different numbers altogether?  In that case: did you refresh the screen in the Eve app?  Did you check the Homebridge log?  Are the numbers correct there?; or
- Are they mixed up (Normal showing the night value and Low showing the day value)?  In that case, please list the telegram as reported by Homebridge P1 during startup.

**Comment by Tangheta** [comment]
According to my meter, 
These are my numbers right now:
1.8.1 Dag Afname : 3,953
1.8.2 Nacht Afname : 24,865
2.8.1 Dag Injectie : 29,496
2.8.2 Nacht Injectie : 1,095

In te Eve app, for the "afname", i get:
Total consumption : 29,10
Total consumption Low : 15,6
Total consumption Normal : 2,3

In the homebridge log, it looks like the totals are only printed now and then for "Electricity delivered" & "Gas".
Not for "Electricity".

**Comment by Tangheta** [comment]
After a restart of the plugin, and refreshing my Eve app, the numbers now seem updated. My bad!
Thanks again for the great plugin!
