### ISSUE TITLE
install on NAS

### ISSUE THREAD

**Issue by Thijsvanzwam** [ebaauw/homebridge-p1#76]
Hi, can you help? I try to install your P1 monitor plugin on my Homebridge installation on a Sinology NAS but without succes. I misses a lot of dependencies and cannot finish the install. I receive the following:

> @serialport/bindings-cpp@10.8.0 install
> node-gyp-build

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.180+
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-p1/node_modules/@serialport/bindings-cpp
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/homebridge-p1/node_modules/@serialport/bindings-cpp
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2023-04-01T10_20_41_314Z-debug-0.log
Failed to rebuild.

Bundled install / update could not complete. Trying regular install / update using npm.

USER: homebridge
DIR: /volume1/homebridge
CMD: npm install --save homebridge-p1@1.3.4

[##################] \ reify:@serialport/bindings-cpp: timing reifyNode:node_modules/h
> @serialport/bindings-cpp@10.8.0 install
> node-gyp-build

gyp ERR! [##################] / reify:@serialport/bindings-cpp: timing reifyNode:node_mbuild error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 4.4.180+
gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-p1/node_modules/@serialport/bindings-cpp
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/homebridge-p1/node_modules/@serialport/bindings-cpp
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2023-04-01T10_20_45_952Z-debug-0.log

Operation failed. Please review log for details.

**Comment by ebaauw** [comment]
I’m afraid I cannot help here.  Homebridge P1 uses the `serialport` repo to interact with the USB serial port provided by the P1 cable.  `serialport` uses a C++ module that needs to be compiled for each system.  It provides pre-compiled binaries for the most common platforms, but, obviously, not for Synology DSM.

I’ve been contemplating ditching `serialport` altogether, in favour of `ser2net`, but that doesn’t run on Synology DSM either.  You would still need a Raspberry Pi or another system to expose the serial port over the network.

**Comment by sbf-** [comment]
> gyp ERR! stack Error: not found: make

To start with, it's `make` that's missing (and after that, C++ compiler and...)
So I guess you have to install `build-essentials`, however, not sure if it is OK to install all this on NAS

**Comment by Thijsvanzwam** [comment]
ok, i see. So no P1 monitor on the Synology then. 
Thanks for your response! I'll close this one.
