### ISSUE TITLE
Not registered as sensor in Homekit

### ISSUE THREAD

**Issue by erikarendsen** [ebaauw/homebridge-p1#8]
Hi Erik, another beautiful project. Keep up the good work! 

Would it be nice that this P1 sensor is also a sensor in Homekit? Now it is indicated as an unsupported accessory. Then you are able to indicate the consumption under the sensor icon (like temperature, lux or [humidity](https://github.com/ageorgios/homebridge-foscam-humidity). If you show 2 x 2 sensors (gas and electricity) with the current consumption and the total consumption, then it is also usable without the Eve App.

Greetings!

**Comment by ebaauw** [comment]
> Would it be nice that this P1 sensor is also a sensor in Homekit?

They are sensors in HomeKit allright (or they wouldn't show in Eve).  This really is a limitation of Apple's Home app.  It simply doesn't support sensors for electrical measurement (like it doesn't support the _Speaker_ service, see https://github.com/ebaauw/homebridge-zp/issues/36).  Same for native HomeKit smart plugs, like the Eve Energy.

I tried exposing the _Electricity_ and _Gas_ services as _Outlet_ in an earlier version of homebridge-p1, so Home would at least expose them as a switch.  Of course you can't switch on or off your meter, so I made them read-only.  After that, Home complained that the accessory needed a firmware update, which makes even less sense than _Not supported_.
