### ISSUE TITLE
Request to Add MQTT Server Option to Homebridge Plugin

### ISSUE THREAD

**Issue by BenouGui** [ebaauw/homebridge-p1#80]
Hello, 

I hope this message finds you well. I'm a user of the Homebridge plugin and have been using it to integrate various devices into my home automation setup. I've recently created a P1 reader based on an Arduino Wemos D1, which receives data from the P1 port and publishes it to an MQTT server. 

I've found your Homebridge plugin to be incredibly useful for my needs. However, I have a feature request that would greatly enhance its functionality. Currently, the plugin communicates with devices over the serial port, which is suitable for many setups. However, it would be incredibly beneficial if there was an option to select an MQTT server for communication instead.

This added functionality would enable users like me to seamlessly integrate MQTT-based devices, like my P1 reader, into Homebridge without the need for additional workarounds or custom scripts. It would greatly simplify the setup process for users who rely on MQTT for their home automation solutions.

I understand that adding this feature might require some effort, but I believe it would be a valuable addition to the Homebridge ecosystem, benefiting many users who rely on MQTT for their smart home projects.

If you could consider adding this MQTT server option to your Homebridge plugin, it would be greatly appreciated. Please let me know if you have any questions or need further information regarding this feature request. I'm more than willing to assist in any way I can to help make this enhancement a reality.

Thank you for your time and for developing such a fantastic plugin. I look forward to hearing from you.

<img width="451" alt="image" src="https://github.com/ebaauw/homebridge-p1/assets/72623517/57e2b1e2-43da-4bf7-99db-b734e92afd80">
Exemple Topic

Sincerely
Benjamin

**Comment by ebaauw** [comment]
Sorry, I won't consider that.  As mentioned in the README, this plugin uses the end-consumer (P1) interface of the Dutch Smart Meter Requirements (DSMR).  I like to keep my setup as simple (and thereby reliable and efficient) as possible and introducing a dependency on an MQTT server would be the opposite.

Also I don't see the need for this, as there's simpler alternatives available:
- By using `ser2net` you can run your MQTT-based P1 reader and Homebrdige P1 in parallel, see https://github.com/ebaauw/homebridge-p1/wiki/Multiple-Concurrent-Connections-to-the-Smart-Meter#using-ser2net-as-relay
- There are several Homebridge plugins for MQTT.  I don't use MQTT myself, and don't know these, but I understand they can be configured to read and write the appropriate topics.  Not sure if they support a smart-plug-like accessory, but that would be a smaller change than adding MQTT support to Homebridge P1.
