### ISSUE TITLE
Endless stream of CRC errors

### ISSUE THREAD

**Issue by wimleers** [ebaauw/homebridge-p1#81]
👋

After running fine for months, my P1 meter (connected using ethernet thanks to https://www.zuidwijk.com/product/p1-reader-ethernet/) was down yesterday. I reconnected it and it was up and running again 👍

The reason I noticed that problem: I checked https://github.com/dsmrreader/dsmr-reader as I went to sleep **two nights ago** and saw that no data had arrived in 15 mins. I then went to the Homebridge log and sure enough, I saw `homebridge-p1` had complained at the same time that the connection was lost. But weirdly, there were lots of CRC errors reported by `homebridge-p1` in the time leading up to the disconnect.

Then this morning I notice that `homebridge-p1` reports lots of errors. So I **reboot it again today.** But the CRC errors keep happening:
![IMG_1011](https://github.com/ebaauw/homebridge-p1/assets/14240/e45252bb-dc82-47b5-9a5a-881b20986d62)

Any idea what could be happening here? 😭

**Comment by wimleers** [comment]
Just tried to look at `homebridge-p1` via the Eve app, which triggered the Eve history code path and that unfortunately hit an error:
![IMG_1015](https://github.com/ebaauw/homebridge-p1/assets/14240/b5a4bd95-b7d1-448c-abf2-2adfba96957b)

**Comment by wimleers** [comment]
I wonder if there's been a firmware update to my P1 meter? 🤔 

In case it helps, here's the latest telegram I've received:
```
\FLU5\253770234_A

0-0:96.1.4(50217)
0-0:96.1.1(3153414731313035333032343531)
0-0:1.0.0(240208085636W)
1-0:1.8.1(001481.212*kWh)
1-0:1.8.2(001958.895*kWh)
1-0:2.8.1(002331.789*kWh)
1-0:2.8.2(000927.621*kWh)
0-0:96.14.0(0001)
1-0:1.4.0(00.167*kW)
1-0:1.6.0(240203161500W)(03.634*kW)
0-0:98.1.0(13)(1-0:1.6.0)(1-0:1.6.0)(230201000000W)(230131191500W)(02.962*kW)(230301000000W)(230215193000W)(02.713*kW)(230401000000S)(230331191500S)(02.583*kW)(230501000000S)(230419201500S)(03.774*kW)(230601000000S)(230509141500S)(03.898*kW)(230701000000S)(230606213000S)(02.409*kW)(230801000000S)(230716134500S)(02.262*kW)(230901000000S)(230824204500S)(02.522*kW)(231001000000S)(230920203000S)(02.222*kW)(231101000000W)(231028151500S)(02.935*kW)(231201000000W)(231130213000W)(04.084*kW)(240101000000W)(231224163000W)(05.462*kW)(240201000000W)(240109034500W)(03.946*kW)
1-0:1.7.0(00.231*kW)
1-0:2.7.0(00.000*kW)
1-0:21.7.0(00.231*kW)
1-0:22.7.0(00.000*kW)
1-0:32.7.0(243.5*V)
1-0:31.7.0(002.25*A)
0-0:96.3.10(1)
0-0:17.0.0(999.9*kW)
1-0:31.4.0(999*A)
0-0:96.13.0()
!BEDD
```

**Comment by ebaauw** [comment]
> I wonder if there's been a firmware update to my P1 meter? 

Don't think so.  I have an old telegram from you that I use for testing the Flemish layout, and that also reports v50217.  It did include gas consumption, though.

https://github.com/ebaauw/homebridge-p1/blob/c83dd331f1380ef590be2f1e8a4951051b3eaa71/lib/telegrams.js#L182-L210

**Comment by wimleers** [comment]
I’m seeing 5–10% packet loss and highly variable latency from my https://www.zuidwijk.com/product/p1-reader-ethernet/, unlike the only other network device in my basement.

DSMR-reader is also reporting matching packet loss problems (but seems to ignore or simply does not rewport CRC errors 🤔 ).

I’ve contacted the manufacturer.

Feel free to close this or keep it open — either way I’ll report back here what I’m told and find out to help out the next person. 👍

**Comment by wimleers** [comment]
FYI it suddenly started working perfectly fine again … the manufacturer has never seen this either 🤷
